config/routes.rb
Rails.application.routes.draw do
  resources :danks
  get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dank.rb
class Dank < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/danks_controller.rb
class DanksController < ApplicationController
  before_action :set_dank, only: [:show, :edit, :update, :destroy]

  # GET /danks
  # GET /danks.json
  def index
    @danks = Dank.all
  end

  # GET /danks/1
  # GET /danks/1.json
  def show
  end

  # GET /danks/new
  def new
    @dank = Dank.new
  end

  # GET /danks/1/edit
  def edit
  end

  # POST /danks
  # POST /danks.json
  def create
    @dank = Dank.new(dank_params)

    respond_to do |format|
      if @dank.save
        format.html { redirect_to @dank, notice: 'Dank was successfully created.' }
        format.json { render :show, status: :created, location: @dank }
      else
        format.html { render :new }
        format.json { render json: @dank.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /danks/1
  # PATCH/PUT /danks/1.json
  def update
    respond_to do |format|
      if @dank.update(dank_params)
        format.html { redirect_to @dank, notice: 'Dank was successfully updated.' }
        format.json { render :show, status: :ok, location: @dank }
      else
        format.html { render :edit }
        format.json { render json: @dank.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /danks/1
  # DELETE /danks/1.json
  def destroy
    @dank.destroy
    respond_to do |format|
      format.html { redirect_to danks_url, notice: 'Dank was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dank
      @dank = Dank.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dank_params
      params.require(:dank).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/danks_helper.rb
module DanksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/danks/_form.html.erb
<%= form_for(dank) do |f| %>
  <% if dank.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dank.errors.count, "error") %> prohibited this dank from being saved:</h2>

      <ul>
      <% dank.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/danks/edit.html.erb
<h1>Editing Dank</h1>

<%= render 'form', dank: @dank %>

<%= link_to 'Show', @dank %> |
<%= link_to 'Back', danks_path %>

app/views/danks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Danks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @danks.each do |dank| %>
      <tr>
        <td><%= dank.name %></td>
        <td><%= link_to 'Show', dank %></td>
        <td><%= link_to 'Edit', edit_dank_path(dank) %></td>
        <td><%= link_to 'Destroy', dank, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dank', new_dank_path %>

app/views/danks/new.html.erb
<h1>New Dank</h1>

<%= render 'form', dank: @dank %>

<%= link_to 'Back', danks_path %>

app/views/danks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dank.name %>
</p>

<%= link_to 'Edit', edit_dank_path(@dank) %> |
<%= link_to 'Back', danks_path %>

app/views/emp_statuses/_form.html.erb
<%= form_for(emp_status) do |f| %>
  <% if emp_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(emp_status.errors.count, "error") %> prohibited this emp_status from being saved:</h2>

      <ul>
      <% emp_status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/emp_statuses/edit.html.erb
<h1>Editing Emp Status</h1>

<%= render 'form', emp_status: @emp_status %>

<%= link_to 'Show', @emp_status %> |
<%= link_to 'Back', emp_statuses_path %>

app/views/emp_statuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Emp Statuses</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @emp_statuses.each do |emp_status| %>
      <tr>
        <td><%= emp_status.status %></td>
        <td><%= link_to 'Show', emp_status %></td>
        <td><%= link_to 'Edit', edit_emp_status_path(emp_status) %></td>
        <td><%= link_to 'Destroy', emp_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Emp Status', new_emp_status_path %>

app/views/emp_statuses/new.html.erb
<h1>New Emp Status</h1>

<%= render 'form', emp_status: @emp_status %>

<%= link_to 'Back', emp_statuses_path %>

app/views/emp_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @emp_status.status %>
</p>

<%= link_to 'Edit', edit_emp_status_path(@emp_status) %> |
<%= link_to 'Back', emp_statuses_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CeramicsPrototype</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>